ShrimplyUI/Models/AddFamilyViewModel.cs
namespace ShrimplyUI.Models
{
    public class AddFamilyViewModel
    {
        public string Name { get; set; }
        public string Code { get; set; }
        public string? ImageUrl { get; set; }
    }
}

ShrimplyUI/Models/Dto/FamilyDto.cs
namespace ShrimplyUI.Models.Dto
{
    public class FamilyDto
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string? ImageUrl { get; set; }
    }
}

ShrimplyUI/Models/ErrorViewModel.cs
namespace ShrimplyUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ShrimplyUI/Controllers/FamilyController.cs
using Microsoft.AspNetCore.Mvc;
using ShrimplyUI.Models;
using ShrimplyUI.Models.Dto;
using System.Text;
using System.Text.Json;

namespace ShrimplyUI.Controllers
{
    public class FamilyController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public FamilyController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<FamilyDto> response = new List<FamilyDto>();
            //get all families from api
            try
            {
                var client = _httpClientFactory.CreateClient();

                var httpResponse = await client.GetAsync("https://localhost:7272/api/family");

                httpResponse.EnsureSuccessStatusCode();

                response.AddRange(await httpResponse.Content.ReadFromJsonAsync<IEnumerable<FamilyDto>>());
            }
            catch (Exception ex)
            {
                //log ex
            }

            return View(response);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(AddFamilyViewModel addFamilyViewModel)
        {
            var client = _httpClientFactory.CreateClient();

            var httpRequestMessage = new HttpRequestMessage()
            {
                Method = HttpMethod.Post,
                RequestUri = new Uri("https://localhost:7272/api/family"),
                Content = new StringContent(JsonSerializer.Serialize(addFamilyViewModel), Encoding.UTF8, "application/json"),
            };

            var httpResponseMessage = await client.SendAsync(httpRequestMessage);
            httpResponseMessage.EnsureSuccessStatusCode();

            var response = await httpResponseMessage.Content.ReadFromJsonAsync<FamilyDto>();

            if (response != null)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var client = _httpClientFactory.CreateClient();

            var response = await client.GetFromJsonAsync<FamilyDto>($"https://localhost:7272/api/family/{id.ToString()}");

            if (response != null)
            {
                return View(response);
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(FamilyDto familyDto)
        {
            var client = _httpClientFactory.CreateClient();
            var httpRequestMessage = new HttpRequestMessage()
            {
                Method = HttpMethod.Put,
                RequestUri = new Uri($"https://localhost:7272/api/family/{familyDto.Id}"),
                Content = new StringContent(JsonSerializer.Serialize(familyDto), Encoding.UTF8, "application/json"),
            };

            var httpResponseMessage = await client.SendAsync(httpRequestMessage);
            httpResponseMessage.EnsureSuccessStatusCode();

            var response = await httpResponseMessage.Content.ReadFromJsonAsync<FamilyDto>();

            if (response != null)
            {
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Delete(FamilyDto familyDto)
        {
            try
            {
                var client = _httpClientFactory.CreateClient();
                var httpResponseMessage = await client.DeleteAsync($"https://localhost:7272/api/family/{familyDto.Id}");

                httpResponseMessage.EnsureSuccessStatusCode();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                //console
            }

            return View("Edit");
        }
    }
}

ShrimplyUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ShrimplyUI.Models;
using System.Diagnostics;

namespace ShrimplyUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ShrimplyUI/Views/Family/Add.cshtml
@using ShrimplyUI.Models.Dto;

@model AddFamilyViewModel

<h1>Add Family</h1>

<form method="post">
    <div>
        <label class="form-label">Name</label>
        <input type="text" asp-for="Name" class="form-control"/>
    </div>
    <div>
        <label class="form-label">Code</label>
        <input type="text" asp-for="Code" class="form-control" />
    </div>
    <div>
        <label class="form-label">Image Url</label>
        <input type="text" asp-for="ImageUrl" class="form-control" />
    </div>
    <div>
        <button type="submit" class="btn btn-primary">Create</button>
        <a class="btn btn-danger" asp-action="Index">Back</a>
    </div>
</form>

ShrimplyUI/Views/Family/Edit.cshtml
@using ShrimplyUI.Models.Dto;
@model FamilyDto

<h1 class="mt-3">Edit Family</h1>

@if (Model != null)
{
    <form method="post">
        <div>
            <label class="form-label">Id</label>
            <input type="text" asp-for="Id" class="form-control" readonly />
        </div>
        <div>
            <label class="form-label">Name</label>
            <input type="text" asp-for="Name" class="form-control" />
        </div>
        <div>
            <label class="form-label">Code</label>
            <input type="text" asp-for="Code" class="form-control" />
        </div>
        <div>
            <label class="form-label">Image Url</label>
            <input type="text" asp-for="ImageUrl" class="form-control" />
        </div>
        <div class="d-flex justify-content-between">
            <button type="submit" class="btn btn-primary">Edit</button>
            <button type="submit" class="btn btn-outline-danger" asp-action="Delete">Delete</button>
            <a class="btn btn-danger" asp-action="Index">Back</a>
        </div>
    </form>
}

ShrimplyUI/Views/Family/Index.cshtml
@using ShrimplyUI.Models.Dto;

@model IEnumerable<FamilyDto>

<h1 class="mt-3">Families</h1>

<div class="d-flex justify-content-end">
    <a class="btn btn-primary" asp-action="Add">Add Family</a>
</div>

<table class="table table-bordered">
    <thead>
    <th>Id</th>
    <th>Name</th>
    <th>Code</th>
    <th>Image Url</th>
    <th></th>
    </thead>
    <tbody>
        @foreach (var family in Model)
        {
            <tr>
                <td>@family.Id</td>
                <td>@family.Name</td>
                <td>@family.Code</td>
                <td>@family.ImageUrl</td>
                <td>
                    <a class="btn btn-secondary" asp-action="Edit" asp-controller="Family" asp-route-id="@family.Id">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>

ShrimplyUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ShrimplyUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShrimplyUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShrimplyUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShrimplyUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Family" asp-action="Index">Families</a>
                        </li>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ShrimplyUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>